# Generated by Django 4.2 on 2025-04-30 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_newsandevents_summary_es_newsandevents_summary_fr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliente", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("empresa", models.CharField(blank=True, max_length=200, null=True)),
                ("descripcion", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("completada", "Completada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "monto_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cotizaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización",
                "verbose_name_plural": "Cotizaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ItemCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("cantidad", models.IntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.cotizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de cotización",
                "verbose_name_plural": "Items de cotización",
            },
        ),
    ]
