# Generated by Django 4.2 on 2025-04-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_cotizacion_itemcotizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="condiciones_pago",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="direccion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_validez",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="notas",
            field=models.TextField(blank=True, null=True),
        ),
    ]
