# Generated by Django 4.2 on 2025-04-30 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0005_cotizacion_condiciones_pago_cotizacion_direccion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cotizacion",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="condiciones_pago",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="email",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="fecha_validez",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="notas",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="telefono",
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="cotizacion",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Cotización"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="dirigido_a",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Dirigido a"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_cotizacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Cotización"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="fecha_servicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha del Servicio"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="modalidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("presencial", "Presencial"),
                    ("virtual", "Virtual"),
                    ("hibrido", "Híbrido"),
                ],
                max_length=20,
                null=True,
                verbose_name="Modalidad",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="modalidad_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("efectivo", "Efectivo"),
                    ("transferencia", "Transferencia"),
                    ("credito", "Crédito"),
                ],
                max_length=20,
                null=True,
                verbose_name="Modalidad de Pago",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="nombre_anio",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nombre del Año"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="ruc",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="RUC"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="sede_servicio",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Sede del Servicio"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="servicio",
            field=models.TextField(blank=True, null=True, verbose_name="Servicio"),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tiempo_entrega",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Tiempo de Entrega"
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="tipo_cotizacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("servicio", "Servicio"),
                    ("producto", "Producto"),
                    ("mixto", "Mixto"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Cotización",
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="validez_cotizacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Validez de Cotización"
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="curso",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Curso"
            ),
        ),
        migrations.AddField(
            model_name="itemcotizacion",
            name="duracion",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Duración"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="empresa",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Empresa"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="estado",
            field=models.CharField(
                default="pendiente", max_length=20, verbose_name="Estado"
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="monto_total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Monto Total"
            ),
        ),
        migrations.AlterField(
            model_name="itemcotizacion",
            name="cantidad",
            field=models.IntegerField(default=1, verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="itemcotizacion",
            name="descripcion",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="itemcotizacion",
            name="precio_unitario",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Precio Unitario"
            ),
        ),
    ]
