# Generated by Django 4.2 on 2025-05-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cotizacion_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cotizacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cotización'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='servicio',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Servicio'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tipo_cotizacion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de Cotización'),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
