# Generated by Django 4.2 on 2025-04-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_course_last_cert_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadvideo",
            options={"ordering": ["order", "timestamp"]},
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Orden en que aparecerá el video (0 = primero)"
            ),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Ingresa la URL del video de YouTube",
                max_length=500,
                null=True,
            ),
        ),
    ]
