# Generated by Django 4.2 on 2025-04-30 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0009_alter_uploadvideo_options_uploadvideo_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadvideo",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Ingresa la URL de YouTube",
                max_length=500,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="VideoCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.uploadvideo",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "unique_together": {("user", "video")},
            },
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="completed_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_videos",
                through="course.VideoCompletion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
