# Generated by Django 4.2 on 2025-04-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0008_course_last_cert_code"),
        ("accounts", "0005_student_cargo_student_empresa"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_students", to="course.course"
            ),
        ),
    ]
